import { expect, test } from './test'

test('highlights drafts', async ({ devPage }) => {
  await devPage.goto()

  const items = await devPage.getSidebarGroupItems('Tests')

  expect(items).toMatchObject([
    { name: 'Not a Draft', badge: null },
    { name: 'Not a Draft', badge: null },
    { name: 'Not a Draft', badge: null },
    { name: 'Draft', badge: 'Draft' },
    { name: 'Draft', badge: 'Draft' },
    { name: 'Draft', badge: 'Draft' },
    {
      label: 'Nested',
      items: [
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
        { name: 'Draft', badge: 'Draft' },
        { name: 'Draft', badge: 'Draft' },
        { name: 'Draft', badge: 'Draft' },
      ],
    },
    {
      label: 'Autogenerated',
      items: [
        { name: 'Draft', badge: 'Draft' },
        { name: 'Draft with Badge', badge: 'New' },
        {
          label: 'nested',
          items: [
            { name: 'Draft', badge: 'Draft' },
            { name: 'Not a Draft', badge: null },
          ],
        },
        { name: 'Not a Draft', badge: null },
      ],
    },
  ])
})
