import { expect, test } from './test'

test('filters drafts', async ({ prodPage }) => {
  await prodPage.goto()

  const items = await prodPage.getSidebarGroupItems('Tests')

  expect(items).toMatchObject([
    { name: 'Not a Draft', badge: null },
    { name: 'Not a Draft', badge: null },
    { name: 'Not a Draft', badge: null },
    {
      label: 'Nested',
      items: [
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
      ],
    },
    {
      label: 'Long',
      items: [
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
        { name: 'Not a Draft', badge: null },
      ],
    },
    {
      label: 'Autogenerated',
      items: [
        {
          label: 'nested',
          items: [{ name: 'Not a Draft', badge: null }],
        },
        { name: 'Not a Draft', badge: null },
      ],
    },
  ])
})
