import type { StarlightPlugin } from '@astrojs/starlight/types'

import { vitePluginStarlightAutoDrafts } from './libs/vite'

export default function starlightAutoDrafts(): StarlightPlugin {
  return {
    name: 'starlight-auto-drafts',
    hooks: {
      'config:setup': ({ addIntegration, addRouteMiddleware, command, config }) => {
        // TODO(HiDeoo) update badge in dev or something
        // if (command !== 'build') return
        // if (!config.sidebar) return

        // TODO(HiDeoo) empty folder
        // TODO(HiDeoo) test autogenerated sidebar groups

        addRouteMiddleware({ entrypoint: 'starlight-auto-drafts/middleware', order: 'post' })

        addIntegration({
          name: 'starlight-auto-drafts-integration',
          hooks: {
            'astro:config:setup': ({ updateConfig }) => {
              updateConfig({
                vite: {
                  plugins: [vitePluginStarlightAutoDrafts(config)],
                },
              })
            },
          },
        })
      },
    },
  }
}
