import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'
import starlightAutoDrafts from 'starlight-auto-drafts'

const site =
  (process.env['CONTEXT'] === 'production' ? process.env['URL'] : process.env['DEPLOY_PRIME_URL']) ??
  'https://starlight-auto-drafts.netlify.app/'

export default defineConfig({
  integrations: [
    starlight({
      customCss: ['./src/styles.css'],
      description:
        'Starlight plugin to tweak draft pages default behavior and automatically remove sidebar links to draft pages in production mode.',
      editLink: {
        baseUrl: 'https://github.com/HiDeoo/starlight-auto-drafts/edit/main/docs/',
      },
      head: [
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: new URL('og.jpg', site).href },
        },
        {
          tag: 'meta',
          attrs: {
            property: 'og:image:alt',
            content:
              'Starlight plugin to tweak draft pages default behavior and automatically remove sidebar links to draft pages in production mode.',
          },
        },
      ],
      routeMiddleware: './src/routeData.ts',
      plugins: [starlightAutoDrafts()],
      sidebar: [
        {
          label: 'Start Here',
          items: ['getting-started', 'configuration'],
        },
        {
          label: 'Guides',
          items: ['guides/custom-highlights'],
        },
        {
          label: 'Resources',
          items: [{ label: 'Plugins and Tools', slug: 'resources/starlight' }],
        },
        {
          label: 'Tests',
          items: [
            'tests/not-a-draft',
            { slug: 'tests/not-a-draft' },
            { label: 'Not a Draft', link: '/tests/not-a-draft/' },
            'tests/draft',
            { slug: 'tests/draft' },
            { label: 'Draft', link: '/tests/draft/' },
            {
              label: 'Nested',
              items: [
                'tests/nested/not-a-draft',
                { slug: 'tests/nested/not-a-draft' },
                { label: 'Not a Draft', link: '/tests/nested/not-a-draft/' },
                'tests/nested/draft',
                { slug: 'tests/nested/draft' },
                { label: 'Draft', link: '/tests/nested/draft/' },
              ],
            },
            {
              label: 'Long',
              items: [
                'tests/long/not-a-draft',
                { slug: 'tests/long/not-a-draft' },
                { label: 'Not a Draft', link: '/tests/long/not-a-draft/' },
                'tests/long/draft',
                { slug: 'tests/long/draft' },
                { label: 'Draft', link: '/tests/long/draft/' },
              ],
            },
            { label: 'Autogenerated', autogenerate: { directory: 'tests/autogenerated' } },
          ],
        },
      ],
      social: [
        { href: 'https://bsky.app/profile/hideoo.dev', icon: 'blueSky', label: 'Bluesky' },
        { href: 'https://github.com/HiDeoo/starlight-auto-drafts', icon: 'github', label: 'GitHub' },
      ],
      title: 'Starlight Auto Drafts',
    }),
  ],
  site,
  trailingSlash: 'always',
})
