import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'
import starlightAutoDrafts from 'starlight-auto-drafts'

export default defineConfig({
  integrations: [
    starlight({
      description: '// TODO(HiDeoo) ',
      editLink: {
        baseUrl: 'https://github.com/HiDeoo/starlight-auto-drafts/edit/main/docs/',
      },
      routeMiddleware: './src/routeData.ts',
      plugins: [starlightAutoDrafts()],
      sidebar: [
        {
          label: 'Start Here',
          items: ['getting-started'],
        },
        // TODO(HiDeoo)
        // {
        //   label: 'Resources',
        //   items: [{ label: 'Plugins and Tools', slug: 'resources/starlight' }],
        // },
        {
          label: 'Tests',
          items: [
            'tests/not-a-draft',
            { slug: 'tests/not-a-draft' },
            { label: 'Not a Draft', link: '/tests/not-a-draft/' },
            'tests/draft',
            { slug: 'tests/draft' },
            { label: 'Draft', link: '/tests/draft/' },
            {
              label: 'Nested',
              items: [
                'tests/nested/not-a-draft',
                { slug: 'tests/nested/not-a-draft' },
                { label: 'Not a Draft', link: '/tests/nested/not-a-draft/' },
                'tests/nested/draft',
                { slug: 'tests/nested/draft' },
                { label: 'Draft', link: '/tests/nested/draft/' },
              ],
            },
            { label: 'Autogenerated', autogenerate: { directory: 'tests/autogenerated' } },
          ],
        },
      ],
      social: [
        { href: 'https://bsky.app/profile/hideoo.dev', icon: 'blueSky', label: 'Bluesky' },
        { href: 'https://github.com/HiDeoo/starlight-auto-drafts', icon: 'github', label: 'GitHub' },
      ],
      title: 'Starlight Auto Drafts',
    }),
  ],
  site: 'https://starlight-auto-drafts.netlify.app/',
  trailingSlash: 'always',
})
